spring:
#  mvc:
#    problemdetails: enabled
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/api_db
    username: api_user
    password: 'pwapi'
  jpa:
    hibernate:
      ddl-auto: create-drop
  admin:
    username: admin
    password: $2a$10$JF.GmZ5gwEJKPpLwGa5FN.L/.ir/KzEt9tTqnvriUJmEyb1BVRTi6